name: Test Workflow
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      uses: YouHao0809/show-ut-coverage/action.yaml
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
